import "server-only";

/** Centralized import and API limits for Google Workspace Phase 6A. */
export const GOOGLE_WORKSPACE_LIMITS = {
  MAX_DOC_STRUCTURAL_ELEMENTS: 5000,
  MAX_DOC_BLOCKS: 200,
  MAX_DOC_TABLE_ROWS: 100,
  MAX_DOC_TABLE_COLUMNS: 20,
  MAX_DOC_TEXT_LENGTH: 500_000,
  MAX_SHEET_ROWS: 2000,
  MAX_SHEET_COLUMNS: 50,
  MAX_CELL_LENGTH: 10_000,
  MAX_IMPORT_WARNINGS: 200,
  MAX_IMPORT_ERRORS: 500,
  MAX_PREVIEW_BYTES: 1_048_576,
  MAX_DRIVE_PAGE_SIZE: 100,
  BOUNDARY_MAX_DEPTH: 40,
} as const;

export type GoogleWorkspaceLimits = typeof GOOGLE_WORKSPACE_LIMITS;
