import type { AssistantRefusalCategory, AssistantRequestStatus } from "./types";

const INSUFFICIENT =
  "В опубликованных материалах недостаточно информации для ответа. Уточните формулировку или откройте обычный поиск.";

const UNAVAILABLE =
  "Ассистент временно недоступен. Попробуйте позже или воспользуйтесь обычным поиском.";

const VALIDATION =
  "Не удалось обработать запрос. Проверьте формулировку вопроса и повторите попытку.";

const RATE_LIMITED =
  "Слишком много запросов. Подождите немного и попробуйте снова.";

/** Server-controlled refusal copy — never generated by the provider. */
export function publicMessageForStatus(
  status: Exclude<AssistantRequestStatus, "answered">,
): string {
  switch (status) {
    case "insufficient_evidence":
      return INSUFFICIENT;
    case "temporarily_unavailable":
      return UNAVAILABLE;
    case "validation_error":
      return VALIDATION;
    case "rate_limited":
      return RATE_LIMITED;
    default:
      return UNAVAILABLE;
  }
}

export function mapRefusalCategoryToStatus(
  category: AssistantRefusalCategory,
): Exclude<AssistantRequestStatus, "answered"> {
  switch (category) {
    case "no_evidence":
    case "incomplete_retrieval":
    case "unsupported_request":
    case "external_information_required":
    case "action_requested":
    case "invalid_provider_response":
    case "missing_citations":
    case "stale_evidence":
    case "provider_refusal":
    case "output_limit_exceeded":
      return "insufficient_evidence";
    case "provider_unavailable":
    case "retrieval_unavailable":
    case "assistant_disabled":
      return "temporarily_unavailable";
    default:
      return "temporarily_unavailable";
  }
}
